### PR TITLE
add .env for webpack and fix asset loading

### PR DESCRIPTION
**Pull request by brandonseydel**

### CODE REVIEW

**Comment by 3cp** [comment]
Thx! Please resolve the conflicts so I can merge it.

**Comment by 3cp** [comment]
I noted vue didn't use dotenv-webpack, they got a nice little internal implementation to handle .env files, directly built on top of dotenv and dotenv-expand.

https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/Service.js

https://cli.vuejs.org/guide/mode-and-env.html#environment-variables

It's quite flexible and convenient to use in my experience with Vue, you can have a base `.env` file, then per mode `.env.development` and `env.production`, and on top of that, a local only `.env.development.local` (not committed to git).

However they did not expose this feature into a standalone webpack plugin, which can be quite useful.

**Comment by ivanbacher** [comment]
Just created a default app

```
✔ Would you like to use the default setup or customize your choices? › Default ESNext Aurelia 2 App
```

 and get this error:

```
Failed to load ./.env.undefined.
```

Shouldn't `.env.development` get loaded by default without having to change anything?

**Comment by 3cp** [comment]
Thx, it was overlooked. Pls try again.

**Comment by ivanbacher** [comment]
No problem. Thanks for the fix.

**Pull request merged**
