### PR TITLE
shadowdom, css-module, and various css features

### PR DESCRIPTION
**Pull request by 3cp**
Support various CSS features

- [x] turn on ShadowDOM and CSS Module
- [x] wait for latest plugin-conventions release, then test all skeletons
- [ ] ~~sass/less/stylus~~ (move following to another PR)
- [ ] ~~postcss~~
- [ ] ~~test all skeletons~~

### CODE REVIEW

**Comment by 3cp** [comment]
@EisenbergEffect if you want, we can release this now without sass/less/stylus/postcss features.

The webpack integration is complete. Dumber needs css-module integration, I am going to do it in next few days.

**Comment by EisenbergEffect** [comment]
Why don't we release after the CSS module integration? Then do a second release for the sass, etc.

**Comment by 3cp** [comment]
Ok

**Comment by 3cp** [comment]
We will implement sass/less/stylus/postcss in another PR.

**Pull request merged**
