### PR TITLE
refactor: use latest styles api

### PR DESCRIPTION
**Pull request by 3cp**
Wait for aurelia/aurelia#804

### CODE REVIEW

**Comment by 3cp** [comment]
@EisenbergEffect there is a complication for webpack setup.

Currently, css (less/scss setup is almost same) imported from html file didn't use style-loader, so that our shadowDom implementation can take control. However, css imported from js file were treated as common webpack use case: use style-loader to inject the css into html page.
```
// @if shadow-dom
{ test: /\.css$/i, issuer: /\.(js|ts)$/, use: [ "style-loader", cssLoader, postcssLoader ] },
{ test: /\.css$/i, issuer: /\.html$/, use: [ "to-string-loader", cssLoader, postcssLoader ] },
// @endif
```

This setup doesn't play were with our API on sharedStyles.

```js
import foo from './foo.css'; // we need to teach webpack to bypass style-loader for this css import
.register(StyleConfiguration.shadowDOM({
    sharedStyles: [ foo ]
  }))
```

I don't have a perfect solution right now. If we disable style-loader for all css imports from js file, we loss that de facto webpack dehaviour.

**Comment by EisenbergEffect** [comment]
@3cp What if we just update the boilerplate so that it includes the proper plugins indicated inline just for the shared styles css.

**Comment by 3cp** [comment]
It's hard to inline `import foo from 'what!ever!plugin!./foo.css';` as user might want postcssLoader (not a simple one line string config) on top of other scss/less loaders as showing in the above config snippet.

**Comment by 3cp** [comment]
Wait a min, I think I can do `issuer: /main\.(js|ts)$/` ...

**Comment by 3cp** [comment]
Question, that if we leave style-loader there, just add to-string-loader

```
{ test: /\.css$/i, issuer: /\.(js|ts)$/, use: [ "to-string-loader", "style-loader", ...
```

```js
// webpack will still inject the css into html head.
// But since this is a shared style, it doesn't really matter.
// Maybe this is a good "feature" for users: apply shared styles to
// all html elements not controlled by shadow dom.
import foo from './foo.css';
.register(StyleConfiguration.shadowDOM({
    sharedStyles: [ foo ]
  }))
```

**Comment by EisenbergEffect** [comment]
@3cp It's not doing that for the html templates though, right?

**Comment by 3cp** [comment]
Nope, the rule is just for css imports in js file.

**Comment by EisenbergEffect** [comment]
I think it could be ok. Do they have a way to manually change that behavior by specifying particular loaders inline or additional webpack config if needed? Is it something we could put in documentation somewhere at some point?

**Comment by 3cp** [comment]
User can use inline loader in code, but that bypasses the pipeline in webpack config. So the inline usage will impose trouble for users with scss/postcss pipelines.
If user uses pure css for those shared styles, inline loader in code is fine.

I would probably document `issuer: /main\.(js|ts)$/` if user wants a way to bypass style-loader for css imported for shared styles.

**Comment by 3cp** [comment]
Passed e2e tests on my mac.

**Comment by 3cp** [comment]
Unfortunately `"to-string-loader", "style-loader"` does not work together. The style-loader change the module format which to-string-loader could not get the original content out.

The result is the shared global style doesn't work in `main.js` for shadow dom setup.

I guess the only choice is to use `issuer: /main\.(js|ts)$/` with some comments.

**Comment by 3cp** [comment]
@EisenbergEffect released on master, please try it out.

**Comment by EisenbergEffect** [comment]
I just ran `npx makes aurelia` and everything seems to work. I did notice that the network panel showed that the entry bundle was 4.4mb. That seems....quite a bit bigger than it should be. I haven't dug into what is going on there yet. Any ideas on that? /cc @fkleuver

**Comment by 3cp** [comment]
I will take a look of the bundle size.

**Comment by 3cp** [comment]
prod build 380k, dev build 3.3M. Your 4.4mb is in browser, probably including source map.

I am trying to understand the dev build in webpack-bundle-analyzer.

**Comment by 3cp** [comment]
@EisenbergEffect It looks correct :D

Both prod build and dev build shows similar list of npm modules.
I knew webpack dev build uses eval string for every modules, but don't know how much is the overhead.

**Comment by EisenbergEffect** [comment]
Is that 380k minified?

**Comment by 3cp** [comment]
Yes, it says stat size 1.1MB (same for prod and dev), the 380k is parsed size.

I guess dev build inflated the original 1.1MB to 3.3M.

**Comment by 3cp** [comment]
With dumber, dev build 1.2M, prod build 580k (probably due to lack of tree-shaking, but I am not exactly sure).
We can see the dev build size is matching webpack stat size.

**Comment by 3cp** [comment]
I think it is tree-shaking. Webpack shook off router, shadow-dom and css-module code.

**Comment by 3cp** [comment]
@EisenbergEffect I added `npm run analyze` to newly created webpack app, you can have a look with a new app.

**Pull request merged**
