### PR TITLE
Update webpack.config.js

### PR DESCRIPTION
**Pull request by brandonseydel**
Need to change to mjs for package resolution since we changed our building strategy.

### CODE REVIEW

**Comment by 3cp** [comment]
@brandonseydel I saw there is some trouble in your hmr code. Pls don't generate ts code, just generate plain js code.

Otherwise, babel setup will fail.

```js
SyntaxError: /tmp/test-skeletons/app-latest-webpack-babel-css-no-unit-tests-cypress-app-min-browser-evergreen/src/my-app.js: Unexpected token, expected "," (10:16)
[84](https://github.com/aurelia/new/runs/6334581493?check_suite_focus=true#step:5:84)

[85](https://github.com/aurelia/new/runs/6334581493?check_suite_focus=true#step:5:85)
   8 |
[86](https://github.com/aurelia/new/runs/6334581493?check_suite_focus=true#step:5:86)
   9 |     const controllers = [];
[87](https://github.com/aurelia/new/runs/6334581493?check_suite_focus=true#step:5:87)
> 10 |     if ((module as any).hot) {
```

**Comment by 3cp** [comment]
@bigopon resolving those dev dist files is just for the core devs?

We probably should not expose this in a user facing skeleton.

**Comment by bigopon** [comment]
@3cp agree, maybe can just move all those to our webpack plugin.

**Comment by 3cp** [comment]
Currently au2 does not have a webpack plugin, it's just a loader.

**Pull request merged**
