### PR TITLE
Change my-app to just app and some QOL webpack stuff

### PR DESCRIPTION
**Pull request by brandonseydel**

### CODE REVIEW

**Comment by 3cp** [comment]
There is a reason for the verbose `<my-app>` tag name.
`<app>` does not work in ShadomDom, ShadowDom requires a dash in custom element tag name like `<my-app>`.

**Comment by 3cp** [comment]
For reference, we have a warning for user on such ShadowDom requirement (It's from ShadowDom spec, not Aurelia):
https://github.com/aurelia/aurelia/blob/b5356ce80cee2022186950ee3d023f5d063ff05a/packages-cjs/plugin-conventions/src/preprocess-html-template.ts#L43

**Comment by zewa666** [comment]
perhaps scaffold the name like `<projectname>-app`?

**Comment by 3cp** [comment]
Yes, app-root sounds better than my-app.

BTW, I don't think "makes"' default project name "my-app" matters. People will change it anyway when creating real project. We can even set default project name to "" to force user to type.

**Comment by brandonseydel** [comment]
@3cp - You give way too much credit.  Developers are not like they used to be.  They leave it out of the box and tack on.  Just like CRA (they don't touch shit)

**Pull request closed without merging**
