### PR TITLE
fixes(gitignore) #22

### PR DESCRIPTION
**Pull request by xenoterracide**
add archives, windows, mac, linux, and nodeignore

### CODE REVIEW

**Comment by 3cp** [comment]
Thx for the contribution, but pls do an audit first. You copied lots of entries not irrelevant in the context of an Aurelia 2 project.

If you want to ignore all of them (regardless of Aurelia 2), pls add to your global gitignore file, as I suggested before.

Grunt, bowser, jspm, 7z, iso, **Next.js, Nuxt.js, Gatsby, vuepress**, Serverless. Why?

```
# Windows Installer files
```
Why in an Aurelia 2 project gitignore?

And some feedback on mac related:
```
# Icon must end with two \r
 Icon
```
I believe most editors (including yours) will normalise line endings to `\n`, which make that entry wrong. (BTW the Icon file might be some legacy stuff, because I am on mac for years, never had any need for that entry in my gitignore).

```
# Files that might appear in the root of a volume
```
Clearly they don't apply to a project folder.

```
# Directories potentially created on remote AFP share
```
Nobody uses AFP, it's deprecated for years.

**Comment by xenoterracide** [comment]
I'll be honest I just copy pasta-ed, but for some of these, like `7z`, and  `iso` and other installer/compression formats. You have no idea how many times in a repo I'll do something like wget, and then forget to exclude, and then commit the thing. This is mostly because I'm never in the directory I think I am. So I'd recommend keeping these as archives are often expensive in the repo, and not everyone is like me and does squash merges, in a regular merge these files will stay around forever.

> Grunt, bower, jspm, Next.js, Nuxt.js, Gatsby, vuepress, Serverless. Why?

I'll be honest, I have no idea what half of these are, but we could probably drop bower, isn't grunt like a task configuration thing? I don't care if we remove them, this is just part of the default node template.

> # Icon must end with two \r
 Icon

afaik, the filename itself must end with 2 \r thanks mac for being weird. if you look at the file (presuming my copy went right, there should be a ^M at the end of Icon)

I can clean this stuff up though. Before I do what do you want to do about the archives/installers?

**Comment by 3cp** [comment]
I would suggest you to use global gitignore, it's so much easier for your case like those zip files.
Add unfamiliar entries here is not going to work.

If you don't know grunt, the simple rule is don't add it.
vuepress and nuxt are Vue, Next.js is React. I don't want to go on to explain other entries... 

I don't think this will work for you, because you started with a big copy/paste, and don't understand the content inside it.

**Comment by xenoterracide** [comment]
k, if you say so

**Comment by 3cp** [comment]
Quite opposite, I am not the rude one.
I will be the rude one if I submit a PR with content I didn't bother to read or understand, and ask someone else to review it for me.
I think my reaction is rather gentle.

**Comment by xenoterracide** [comment]
I read and understood 95% of it, I guess there are a couple of things I didn't clip that I knew weren't necessary, but the original discussion was to add the full templates. Just because I haven't/don't use a technology doesn't mean ignoring it isn't the right solution.

**Comment by 3cp** [comment]
Why I want to ignore vue files in my au2 project folder?

**Comment by xenoterracide** [comment]
I didn't say you would, but I asked what you wanted to do with archives before cleaning that up. That way I could make all the changes asked for at once. The rude thing here, is closing the PR without giving me a chance to clean up what you were asking for. I'm going to stop now though, this conversation doesn't seem like it can be productive at this point. you closed it, that's fine.

I only suggested this feature because of 2 things 1, I didn't actually know about global gitignore, I'm definitely going to add one soon, but 2, I REALLY do NOT TRUST me, or my COLLEAGUES not to commit things like Thumbs.db, zip files, log files, etc. I definitely don't expect them to have a smart global ignore.

**Comment by 3cp** [comment]
When I offered my feedback because I thought you at least went through the content, you admit "just copy pasta-ed" and "have no idea what half of these" (these for grunt ... Serverless). That's where you turned me off.

You didn't bother to at least google the stuff you don't understand. Why should I be interested to be your human google?

The conversation could have been started much better if you highlighted few things you were not sure after some basic investigation.

> The rude thing here, is closing the PR without giving me a chance to clean up what you were asking for.

You did not give yourself the chance. It that few mins study (googling) too troublesome? Or you just want to "let me send the PR to see what happens"? How can you talk down your colleagues since you are careless?

> 1, I didn't actually know about global gitignore

https://github.com/aurelia/new/issues/22#issuecomment-616254953

> I REALLY do NOT TRUST me, or my COLLEAGUES

Should I trust your work since you do not trust yourself? Nobody understands everything, nobody makes no mistake. But lack of basic effort wound not work in any team.

**Pull request closed without merging**
